[package]
name = "linfa-ensemble"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linfa = { version = "0.7.0", path = "../.." }
linfa-trees = { version = "0.7.0", path = "../linfa-trees"}
ndarray = { version = "0.15" , features = ["rayon", "approx"]}

linfa-datasets = { version = "0.7.0", path = "../../datasets/", features = ["iris"] }
ndarray-rand = "0.14"

[dev-dependencies]
rand = { version = "0.8", features = ["small_rng"] }
linfa-datasets = { version = "0.7.0", path = "../../datasets/", features = ["iris"] }